Python3: `read` and `write` return/take unicode strings
This fixes:

> TypeError: write() argument 1 must be unicode, not str

Python 3's `open` (and our `builtins.open` backport) defaults to "text
mode" if the mode string is "r" or "w" (binary mode would be "rb" or
"wb").

In text mode `write` takes unicode (in binary mode `write` takes a
bytestring).

In text mode, `open` takes an optional `encoding` parameter. It
defaults to `locale.getpreferredencoding(do_setlocale=False)`, which is
"UTF-8" on my laptop where LANG=en_GB.UTF-8.